apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: broker
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: broker
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: broker
    spec:
      containers:
        - env:
            - name: CONFLUENT_PLUGIN_PATH
              value: /connect-plugins
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://broker:19092,PLAINTEXT_HOST://
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL
              value: http://schema-registry:8081
            - name: KAFKA_CREATE_TOPICS
              value: TestOtw:1:1, TestFundsAuth:1:1, streams-pipe-output:1:1
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
          image: confluentinc/cp-server:5.5.5
          name: broker
          ports:
            - containerPort: 9092
            - containerPort: 9101
          resources: {}
      hostname: broker
      restartPolicy: Always
status: {}
