version: '3.3'

services:

  zookeeper:

    image: confluentinc/cp-zookeeper:5.5.5

    hostname: zookeeper

    container_name: zookeeper

    ports:

      - "2181:2181"

    environment:

      ZOOKEEPER_CLIENT_PORT: 2181

      ZOOKEEPER_TICK_TIME: 2000

 

  broker:

    image: confluentinc/cp-server:5.5.5

    hostname: broker

    container_name: broker

    depends_on:

      - zookeeper

    ports:

      - "9092:9092"

      - "9101:9101"

    environment:

      KAFKA_CREATE_TOPICS: "TestOtw:1:1, TestFundsAuth:1:1, streams-pipe-output:1:1"

      KAFKA_BROKER_ID: 1

      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:19092,PLAINTEXT_HOST://${BOOTSTRAP_SERVERS_CONFIG}

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081

      CONFLUENT_PLUGIN_PATH: /connect-plugins

 

  schema-registry:

    image: confluentinc/cp-schema-registry:5.5.5

    hostname: schema-registry

    container_name: schema-registry

    depends_on:

      - zookeeper

      - broker

    ports:

      - "8081:8081"

    environment:

      SCHEMA_REGISTRY_HOST_NAME: schema-registry

      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'

 

  connect:

    image: confluentinc/cp-kafka-connect:5.5.5

    hostname: connect

    container_name: connect

    depends_on:

      - zookeeper

      - broker

      - schema-registry

    ports:

      - "8083:8083"

    environment:

      CONNECT_BOOTSTRAP_SERVERS: 'broker:19092'

      CONNECT_REST_ADVERTISED_HOST_NAME: connect

      CONNECT_REST_PORT: 8083

      CONNECT_GROUP_ID: compose-connect-group

      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs

      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1

      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000

      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets

      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1

      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status

      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1

      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter

      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.storage.StringConverter

      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081

      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter

      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter

      CONNECT_INTERNAL_KEY_CONVERTER_SCHEMAS_ENABLE: 'false'

      CONNECT_INTERNAL_VALUE_CONVERTER_SCHEMAS_ENABLE: 'false'

      CONNECT_ZOOKEEPER_CONNECT: 'zookeeper:2181'

      CLASSPATH: /usr/share/java/monitoring-interceptors/monitoring-interceptors-5.5.1.jar

      CONNECT_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"

      CONNECT_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"

      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components,/connect-plugins"

      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR

      CONNECT_CONNECTOR_CLIENT_CONFIG_OVERRIDE_POLICY: 'All'

      KAFKA_OPTS: "-Doracle.jdbc.timezoneAsRegion=false -Duser.timezone=Pacific/Auckland"

    volumes:

      - "./connect-plugins/confluentinc-kafka-connect-ibmmq-11.0.8:/connect-plugins/kafka-connect-ibmmq"

      - "./ibm-mq-jars/wmq/JavaSE/lib:/connect-plugins/kafka-connect-ibmmq/mq"




  rest-proxy:

    image: confluentinc/cp-kafka-rest:5.5.5

    hostname: rest-proxy

    depends_on:

      - zookeeper

      - broker

      - schema-registry

    ports:

      - 8082:8082

    environment:

      KAFKA_REST_HOST_NAME: rest-proxy

      KAFKA_REST_BOOTSTRAP_SERVERS: 'broker:19092'

      KAFKA_REST_LISTENERS: http://0.0.0.0:8082

      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'

 

  ibmmq:

    image: ibmcom/mq

    hostname: ibmmq

    environment:

      - LICENSE=accept

      - MQ_QMGR_NAME=QM1

      - MQ_APP_PASSWORD=devpw

    ports:

      - 1414:1414

      - 9443:9443

    privileged: true