apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: ibmmq
  name: ibmmq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ibmmq
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: ibmmq
    spec:
      containers:
        - env:
            - name: LICENSE
              value: accept
            - name: MQ_APP_PASSWORD
              value: devpw
            - name: MQ_QMGR_NAME
              value: QM1
          image: ibmcom/mq
          name: ibmmq
          ports:
            - containerPort: 1414
            - containerPort: 9443
          resources: {}
          securityContext:
            privileged: true
      hostname: ibmmq
      restartPolicy: Always
status: {}
