apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: ibmmq
  name: ibmmq
spec:
  ports:
    - name: "1414"
      port: 1414
      targetPort: 1414
    - name: "9443"
      port: 9443
      targetPort: 9443
  selector:
    io.kompose.service: ibmmq
status:
  loadBalancer: {}
